import { Raga, Thaat } from './types';

export const THAAT_DATA: Thaat[] = [
    { id: "bilawal", name: "Bilawal", notes: ["Sa","Re","Ga","ma","Pa","Dha","Ni"] },
    { id: "kalyan", name: "Kalyan", notes: ["Sa","Re","Ga","Ma","Pa","Dha","Ni"] },
    { id: "khamaj", name: "Khamaj", notes: ["Sa","Re","Ga","ma","Pa","Dha","ni"] },
    { id: "kafi", name: "Kafi", notes: ["Sa","Re","ga","ma","Pa","Dha","ni"] },
    { id: "asavari", name: "Asavari", notes: ["Sa","Re","ga","ma","Pa","dha","ni"] },
    { id: "bhairavi", name: "Bhairavi", notes: ["Sa","re","ga","ma","Pa","dha","ni"] },
    { id: "bhairav", name: "Bhairav", notes: ["Sa","re","Ga","ma","Pa","dha","Ni"] },
    { id: "poorvi", name: "Poorvi", notes: ["Sa","re","Ga","Ma","Pa","dha","Ni"] },
    { id: "marwa", name: "Marwa", notes: ["Sa","re","Ga","Ma","Pa","Dha","Ni"] },
    { id: "todi", name: "Todi", notes: ["Sa","re","ga","Ma","Pa","dha","Ni"] }
];

export const RAGA_DATA: Raga[] = [
    {
        num: 1,
        id: "desi",
        name: "Desi",
        thaat: "Asavari",
        aaroh: ["Sa","Re","ma","Pa","Dha","ni","Sa"],
        avaroh: ["Sa","Pa","Dha","ma","Pa","Re","ga","Re","Sa"],
        pakad: [["Pa","Re","ga","Re","Sa","ni","Sa"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        identifyingFeature: "Mixes Shuddha and Komal Dha",
        phrases: [
            ["Sa","Re","ma","Pa"],
            ["ma","Pa","Dha","ma","Pa"],
            ["Dha","Pa","ma","Pa","Re","ga","Sa"],
            ["Re","ni","Sa","Re","ga","Sa"],
            ["Pa","ma","Pa","Re","ga","Sa"],
            ["Sa","Re","ma","Pa","Dha","ma","Pa"],
            ["ma","Pa","ni","Dha","Pa"],
            ["Pa","Dha","ma","Pa","ga","Sa"],
            ["Re","ma","Pa","Dha","ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","Pa","ga","Sa"]
        ]
    },
    {
        num: 2,
        id: "nat_bhairav",
        name: "Nat Bhairav",
        thaat: "Bhairav",
        aaroh: ["Sa","Re","Ga","ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","ma","Ga","Re","Sa"],
        pakad: [["ma","Pa","dha","Ni","Sa","Ni","dha","Pa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Shuddha Re in Bhairav scale",
        phrases: [
            ["Sa","Re","Ga","ma","Pa"],
            ["ma","Pa","dha","Ni","Sa"],
            ["Sa","Ni","dha","Pa"],
            ["ma","Ga","Re","Sa"],
            ["Sa","Re","Ga","ma","Pa","dha","Pa"],
            ["Ga","ma","dha","Ni","Sa"],
            ["Ni","Sa","dha","Ni","dha","Pa"],
            ["Ga","ma","Pa","ma","Ga","Re","Sa"],
            ["Sa","Re","Ga","ma","Re","Sa"],
            ["Pa","dha","Ni","Sa","Re","Sa"]
        ]
    },
    {
        num: 3,
        id: "bairagi",
        name: "Bairagi",
        thaat: "Bhairav",
        aaroh: ["Sa","re","ma","Pa","ni","Sa"],
        avaroh: ["Sa","ni","Pa","ma","re","Sa"],
        pakad: [["ni","Pa","ma","re","ni","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Pentatonic Bhairav (Revati with Komal Ni)",
        phrases: [
            ["Sa","re","ma","Pa"],
            ["ma","Pa","ni","Sa"],
            ["Sa","ni","Pa","ma"],
            ["Pa","ma","re","Sa"],
            ["ni","Sa","re","ma","Pa"],
            ["ma","Pa","ni","Sa","ni","Pa"],
            ["re","ma","Pa","ni","Pa","ma"],
            ["Sa","re","Sa","ni","Pa"],
            ["Pa","ni","Sa","re","ma"],
            ["ni","Pa","ma","re","ma","Pa"]
        ]
    },
    {
        num: 4,
        id: "kalingara",
        name: "Kalingara",
        thaat: "Bhairav",
        aaroh: ["Sa","re","Ga","ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","ma","Ga","re","Sa"],
        pakad: [["ma","Pa","dha","Ni","Sa"],["Pa","ma","Ga","re","Ga"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        identifyingFeature: "Lighter, playful Bhairav (no oscillation)",
        phrases: [
            ["Sa","re","Ga","ma","Pa"],
            ["Ga","ma","Pa","dha","Ni","Sa"],
            ["Sa","Ni","dha","Pa","ma","Ga","re","Sa"],
            ["Pa","dha","Ni","dha","Pa"],
            ["ma","Pa","dha","Pa","ma","Ga"],
            ["Ga","ma","Ga","re","Sa"],
            ["Sa","re","Ga","ma","Pa","ma","Ga"],
            ["Pa","dha","Ni","Sa","Ni","dha","Pa"],
            ["ma","Ga","re","Ga","Sa"],
            ["dha","Ni","Sa","re","Ga","re","Sa"]
        ]
    },
    {
        num: 5,
        id: "poorvi",
        name: "Poorvi",
        thaat: "Poorvi",
        aaroh: ["Sa","re","Ga","Ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","Ma","Ga","re","Sa"],
        pakad: [["Pa","dha","Ma","Ga","re","Ga"],["Ma","dha","Ni","Sa"]],
        vaadi: "Ga",
        samvaadi: "Ni",
        identifyingFeature: "Uses both Mas sometimes, deeply serious",
        phrases: [
            ["Sa","re","Ga","Ma","Pa"],
            ["Ma","Pa","dha","Ni","Sa"],
            ["Sa","Ni","dha","Pa"],
            ["Ma","Ga","re","Sa"],
            ["Pa","dha","Pa","Ma","Ga"],
            ["Ma","Pa","dha","Ni","dha","Pa"],
            ["re","Ga","Ma","Pa","Ma","Ga"],
            ["Ni","Sa","re","Ga","re","Sa"],
            ["Pa","Ma","Ga","Ma","re","Ga"],
            ["dha","Ni","Sa","re","Ni","dha","Pa"]
        ]
    },
    {
        num: 6,
        id: "gujari_todi",
        name: "Gujari Todi",
        thaat: "Todi",
        aaroh: ["Sa","re","ga","Ma","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Ma","ga","re","Sa"],
        pakad: [["dha","Ma","ga","re","ga","re","Sa"]],
        vaadi: "dha",
        samvaadi: "re",
        identifyingFeature: "Todi without Pa (Hexatonic)",
        phrases: [
            ["Sa","re","ga","Ma","dha"],
            ["Ma","dha","Ni","Sa"],
            ["Sa","Ni","dha","Ma","ga","re","Sa"],
            ["dha","Ni","Sa","re","ga","re","Sa"],
            ["Ma","dha","Ni","dha","Ma"],
            ["ga","Ma","dha","Ma","ga","re"],
            ["re","ga","Ma","dha","Ni"],
            ["Ni","dha","Ma","ga","re","ga","Ma"],
            ["Sa","re","ga","re","Sa"],
            ["dha","Ni","Sa","re","ga","Ma"]
        ]
    },
    {
        num: 7,
        id: "madhuvanti",
        name: "Madhuvanti",
        thaat: "Todi",
        aaroh: ["Sa","ga","Ma","Pa","Ni","Sa"],
        avaroh: ["Sa","Ni","Dha","Pa","Ma","ga","Re","Sa"],
        pakad: [["Ni","Sa","ga","Ma","Pa"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        identifyingFeature: "Sweetness of honey (Madhu)",
        phrases: [
            ["Ni","Sa","ga","Ma","Pa"],
            ["Ma","Pa","Ni","Sa"],
            ["Sa","Ni","Dha","Pa","Ma","ga","Re","Sa"],
            ["ga","Ma","Pa","Ni","Sa"],
            ["Pa","Ni","Sa","ga","Re","Sa"],
            ["Ni","Sa","ga","Ma","Pa","Dha","Pa"],
            ["Ma","Pa","Ni","Sa","Ni","Dha","Pa"],
            ["ga","Ma","Pa","ga","Ma","ga","Re","Sa"],
            ["Pa","Ni","Sa","ga","Ma","Pa"],
            ["Ni","Dha","Pa","Ma","ga","Re"]
        ]
    },
    {
        num: 8,
        id: "bilaskhani_todi",
        name: "Bilaskhani Todi",
        thaat: "Bhairavi",
        aaroh: ["Sa","re","ga","Pa","dha","Sa"],
        avaroh: ["Sa","ni","dha","Pa","ma","ga","re","Sa"],
        pakad: [["dha","Pa","ma","ga","re","ga","re","Sa"]],
        vaadi: "dha",
        samvaadi: "ga",
        phrases: [
            ["Sa","re","ga","Pa","dha","Sa"],
            ["ni","dha","Pa","ma","ga","re","Sa"],
            ["ga","Pa","dha","Sa","re","Sa"],
            ["ni","dha","Pa","ma","ga","re"],
            ["dha","Pa","ma","ga","re","Sa"],
            ["Sa","re","ga","Pa","dha","Sa"],
            ["Sa","ni","dha","Pa"],
            ["dha","Pa","ma","ga","re","Sa"],
            ["re","ni","Sa","re","ga","Pa"],
            ["ga","Pa","dha","Sa","ni","dha","Pa"],
            ["dha","Pa","ma","ga","re","ga","re","Sa"],
            ["re","ga","Pa","dha","ni","dha","Pa"],
            ["Sa","re","ga","Pa","ma","ga","re","Sa"],
            ["Pa","dha","Sa","re","ga","re","Sa"],
            ["ni","dha","Pa","ma","ga","re","Sa"]
        ]
    },
    {
        num: 9,
        id: "yaman",
        name: "Yaman",
        thaat: "Kalyan",
        aaroh: ["Ni","Re","Ga","Ma","Dha","Ni","Sa"],
        avaroh: ["Sa","Ni","Dha","Pa","Ma","Ga","Re","Sa"],
        pakad: [["Ni","Re","Ga","Re","Sa","Pa","Ma","Ga","Re","Sa"]],
        vaadi: "Ga",
        samvaadi: "Ni",
        phrases: [
            ["Ni","Re","Ga","Re","Sa"],
            ["Ma","Pa","Dha","Ni","Sa"],
            ["Pa","Ma","Ga","Re","Ni","Re","Sa"],
            ["Ni","Dha","Pa","Ma","Ga"],
            ["Ga","Ma","Pa","Re","Sa"],
            ["Ni","Re","Ga","Ma","Pa"],
            ["Ma","Dha","Ni","Sa"],
            ["Sa","Ni","Dha","Pa","Ma","Ga","Re","Sa"],
            ["Ni","Re","Ga","Ma","Pa","Dha","Ni","Sa"],
            ["Pa","Ma","Ga","Re","Sa"],
            ["Ni","Re","Sa","Ni","Dha","Pa"],
            ["Ma","Dha","Ni","Dha","Pa"],
            ["Ga","Ma","Pa","Ma","Ga","Re"],
            ["Ni","Re","Ga","Ma","Pa","Ma","Ga"],
            ["Pa","Dha","Ni","Sa","Ni","Dha","Pa"]
        ]
    },
    {
        num: 10,
        id: "bhupali",
        name: "Bhupali",
        thaat: "Kalyan",
        aaroh: ["Sa","Re","Ga","Pa","Dha","Sa"],
        avaroh: ["Sa","Dha","Pa","Ga","Re","Sa"],
        pakad: [["Sa","Re","Ga","Pa","Ga","Re","Sa"]],
        vaadi: "Ga",
        samvaadi: "Dha",
        phrases: [
            ["Ga","Pa","Dha","Sa","Dha","Pa","Ga"],
            ["Sa","Re","Ga","Pa","Ga","Re","Sa"],
            ["Pa","Ga","Dha","Pa","Ga","Re","Sa"],
            ["Sa","Dha","Pa","Ga","Re","Sa","Dha","Sa"],
            ["Dha","Sa","Re","Ga","Pa"],
            ["Sa","Re","Ga","Pa","Dha","Sa"],
            ["Sa","Dha","Pa","Ga","Re","Sa"],
            ["Ga","Pa","Dha","Sa","Dha","Pa"],
            ["Sa","Re","Ga","Pa","Ga","Re","Sa"],
            ["Pa","Dha","Sa","Re","Sa","Dha","Pa"],
            ["Ga","Pa","Dha","Pa","Ga","Re"],
            ["Sa","Re","Ga","Re","Sa","Dha"],
            ["Dha","Sa","Re","Ga","Pa"],
            ["Ga","Pa","Dha","Sa","Re","Ga","Re","Sa"],
            ["Pa","Ga","Dha","Pa","Ga","Re","Sa"]
        ]
    },
    {
        num: 11,
        id: "shivranjani",
        name: "Shivranjani",
        thaat: "Kafi",
        aaroh: ["Sa","Re","ga","Pa","Dha","Sa"],
        avaroh: ["Sa","Dha","Pa","ga","Re","Sa"],
        pakad: [["Sa","Re","ga","Pa","Dha","Pa","ga","Re","Sa"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        phrases: [
            ["Re","ga","Pa","Dha","Pa","ga","Re"],
            ["Sa","Re","ga","Pa","Dha","Sa"],
            ["Dha","Pa","ga","Re","Sa"],
            ["ga","Re","Sa","Dha","Sa"],
            ["Pa","Dha","Sa","Re","ga","Re","Sa"],
            ["Sa","Re","ga","Pa","Dha","Sa"],
            ["Sa","Dha","Pa","ga","Re","Sa"],
            ["Re","ga","Pa","Dha","Pa","ga","Re"],
            ["Sa","Re","ga","Pa","ga","Re","Sa"],
            ["Pa","Dha","Sa","Re","ga","Re","Sa"],
            ["ga","Pa","Dha","Sa","Dha","Pa"],
            ["Sa","Re","ga","Sa","Dha","Pa"],
            ["Dha","Sa","Re","ga","Pa","Dha"],
            ["ga","Pa","Dha","Sa","Re","Sa"],
            ["Pa","Dha","Pa","ga","Re","Sa"]
        ]
    },
    {
        num: 12,
        id: "bhairav",
        name: "Bhairav",
        thaat: "Bhairav",
        aaroh: ["Sa","re","Ga","ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","ma","Ga","re","Sa"],
        pakad: [["Ga","ma","dha","Pa"]],
        vaadi: "dha",
        samvaadi: "re",
        phrases: [
            ["Ga","ma","dha","dha","Pa"],
            ["Ga","ma","re","re","Sa"],
            ["Ni","re","Sa","Ga","ma","Pa"],
            ["Pa","Ga","ma","dha","Ni","Sa"],
            ["dha","dha","Pa","ma","Ga","ma","re","Sa"],
            ["Sa","re","Ga","ma","Pa"],
            ["Ga","ma","dha","Pa"],
            ["dha","dha","Pa"],
            ["Ga","ma","re","re","Sa"],
            ["Ni","Sa","re","Ga","ma","Pa"],
            ["Pa","dha","Ni","Sa"],
            ["Sa","Ni","dha","Pa","ma","Ga","re","Sa"],
            ["Ga","ma","Pa","dha","Pa"],
            ["ma","Pa","Ga","ma","re","Sa"],
            ["Ni","re","Sa","Ga","ma","Pa"]
        ]
    },
    {
        num: 13,
        id: "desh",
        name: "Desh",
        thaat: "Khamaj",
        aaroh: ["Sa","Re","ma","Pa","Ni","Sa"],
        avaroh: ["Sa","ni","Dha","Pa","ma","Ga","Re","Ga","Sa"],
        pakad: [["Re","ma","Pa","ni","Dha","Pa"]],
        vaadi: "Re",
        samvaadi: "Pa",
        phrases: [
            ["Re","ma","Pa","Ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","Ga","Re"],
            ["Re","Ga","Sa","Re","ma","Ga"],
            ["Pa","Dha","Pa","ma","Ga","Re","Ga","Sa"],
            ["Ni","Sa","Re","ni","Dha","Pa"],
            ["Sa","Re","ma","Pa","Ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","Ga","Re","Sa"],
            ["Re","ma","Pa","Ni","Dha","Pa"],
            ["ma","Pa","ni","Dha","Pa"],
            ["Dha","Pa","ma","Ga","Re","Ga","Sa"],
            ["Re","ma","Pa","Ni","Sa","Re","ni","Dha","Pa"],
            ["Ni","Sa","Re","ni","Dha","Pa"],
            ["ma","Pa","Ni","Sa"],
            ["Sa","Re","ma","Ga","Re","Sa"],
            ["Pa","Dha","Pa","ma","Ga","Re","Sa"]
        ]
    },
    {
        num: 14,
        id: "durga",
        name: "Durga",
        thaat: "Bilawal",
        aaroh: ["Sa","Re","ma","Pa","Dha","Sa"],
        avaroh: ["Sa","Dha","Pa","ma","Re","Sa"],
        pakad: [["Dha","ma","Pa","Dha","ma","Re"]],
        vaadi: "ma",
        samvaadi: "Sa",
        phrases: [
            ["Sa","Re","ma","Pa","Dha","Sa"],
            ["Dha","Pa","ma","Re","Sa"],
            ["ma","Pa","Dha","ma","Re","Sa"],
            ["Sa","Re","Sa","Dha","Sa"],
            ["Dha","Sa","Dha","Pa","ma","Re"],
            ["Sa","Re","ma","Pa","Dha","Sa"],
            ["Sa","Dha","Pa","ma","Re","Sa"],
            ["ma","Pa","Dha","Sa","Dha","Pa"],
            ["Dha","ma","Pa","Dha","ma","Re"],
            ["Sa","Re","ma","Pa","ma","Re","Sa"],
            ["Dha","Sa","Re","ma","Re","Sa"],
            ["ma","Pa","Dha","Sa","Re","Sa","Dha","Pa"],
            ["Pa","Dha","ma","Pa","ma","Re"],
            ["Sa","Re","Sa","Dha","Sa"],
            ["Dha","Pa","ma","Re","ma","Pa","Dha","Sa"]
        ]
    },
    {
        num: 15,
        id: "kedar",
        name: "Kedar",
        thaat: "Kalyan",
        aaroh: ["Sa","ma","Ga","Pa","Ni","Dha","Sa"],
        avaroh: ["Sa","Ni","Dha","Pa","Ma","Pa","Dha","Pa","ma","Re","Sa"],
        pakad: [["Sa","ma","Ga","Pa","ma","Re","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        phrases: [
            ["Sa","ma","Ga","Pa"],
            ["Ma","Pa","Dha","Pa","ma"],
            ["Pa","ma","Re","Sa"],
            ["Sa","Ni","Dha","Pa"],
            ["Dha","Pa","Ma","Pa","Ga","ma","Re","Sa"],
            ["Sa","ma","Ga","Pa"],
            ["ma","Pa","Dha","Pa","ma"],
            ["Pa","ma","Re","Sa"],
            ["Sa","ma","Ga","Pa","ma","Dha","Pa"],
            ["Dha","Ni","Dha","Pa"],
            ["Sa","Re","Sa","ma","Ga","Pa"],
            ["ma","Pa","Dha","Pa","Ma","Pa","Dha","Pa","ma"],
            ["Pa","ma","Re","Sa","Re","Sa"],
            ["Sa","ma","Ga","Pa","Ni","Dha","Sa"],
            ["Sa","Ni","Dha","Pa","ma","Ga","Pa","ma","Re","Sa"]
        ]
    },
    {
        num: 16,
        id: "bageshri",
        name: "Bageshri",
        thaat: "Kafi",
        aaroh: ["Sa","ga","ma","Dha","ni","Sa"],
        avaroh: ["Sa","ni","Dha","ma","Pa","Dha","ga","Re","Sa"],
        pakad: [["Dha","ni","Sa","ma","ga","Re","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        phrases: [
            ["Sa","ga","ma","Dha","ni","Sa"],
            ["Sa","ni","Dha","ma","Pa","Dha","ga"],
            ["ma","Pa","Dha","ni","Dha","ma"],
            ["ga","Re","Sa","ni","Dha","Sa"],
            ["Dha","ni","Sa","ma","ga","Re","Sa"],
            ["Sa","ga","ma","Dha","ni","Sa"],
            ["Sa","ni","Dha","ma","Pa","Dha","ga","ma","ga","Re","Sa"],
            ["Dha","ni","Sa","ma","ga","ma"],
            ["ga","ma","Dha","ni","Dha","ma"],
            ["ma","Pa","Dha","ga","ma","ga","Re","Sa"],
            ["ni","Dha","ma","Pa","Dha","ni","Sa"],
            ["Sa","ni","Dha","ma","ga","Re","Sa"],
            ["ga","ma","Dha","ni","Sa","ni","Dha"],
            ["ma","Dha","ni","Dha","ma","ga","Re"],
            ["Sa","ga","ma","ga","Re","Sa"]
        ]
    },
    {
        num: 17,
        id: "bhimpalasi",
        name: "Bhimpalasi",
        thaat: "Kafi",
        aaroh: ["ni","Sa","ga","ma","Pa","ni","Sa"],
        avaroh: ["Sa","ni","Dha","Pa","ma","ga","Re","Sa"],
        pakad: [["ni","Sa","ga","ma","Pa","ga","ma","ga","Re","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        phrases: [
            ["ni","Sa","ma","Pa","ga","ma"],
            ["ma","Pa","ni","Dha","Pa"],
            ["Pa","ma","ga","Re","Sa"],
            ["Sa","ni","Dha","Pa","ma","ga","Re"],
            ["ni","Sa","ga","ma","Pa","ni","Sa"],
            ["ni","Sa","ga","ma","Pa","ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","ga","Re","Sa"],
            ["ni","Sa","ma","Pa","ga","ma"],
            ["ma","Pa","ni","Dha","Pa"],
            ["Pa","ma","ga","Re","Sa"],
            ["ni","Sa","ga","ma","Pa"],
            ["Pa","ni","Sa","ga","Re","Sa"],
            ["ma","Pa","ga","ma","Pa","ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","Pa","ga","ma"],
            ["ga","ma","Pa","ni","Dha","Pa"]
        ]
    },
    {
        num: 18,
        id: "darbari",
        name: "Darbari Kanada",
        thaat: "Asavari",
        aaroh: ["Sa","Re","ga","ma","Pa","dha","ni","Sa"],
        avaroh: ["Sa","dha","ni","Pa","ma","Pa","ga","ma","Re","Sa"],
        pakad: [["ni","Pa","ma","Pa","ga","ma","Re","Sa"]],
        vaadi: "Re",
        samvaadi: "Pa",
        phrases: [
            ["Sa","Re","ga","ma","Pa"],
            ["dha","ni","Pa","ma","Pa"],
            ["ga","ma","Re","Sa"],
            ["Pa","dha","ni","Sa"],
            ["Sa","dha","ni","Pa","ga","ma","Re","Sa"],
            ["ni","Sa","Re","ga","Re","Sa"],
            ["dha","ni","Pa","ma","Pa","ga","ma","Re","Sa"],
            ["Sa","Re","ga","ma","Pa"],
            ["Pa","dha","ni","Pa","ma","Pa"],
            ["ga","ma","Re","Sa"],
            ["Sa","dha","ni","Pa"],
            ["Pa","ma","Pa","ga","ma","Re","Sa"],
            ["ni","Sa","Re","ga","ma","Pa"],
            ["dha","ni","Sa","Re","ga","Re","Sa"],
            ["ma","Pa","dha","ni","Sa"]
        ]
    },
    {
        num: 19,
        id: "jaunpuri",
        name: "Jaunpuri",
        thaat: "Asavari",
        aaroh: ["Sa","Re","ma","Pa","dha","ni","Sa"],
        avaroh: ["Sa","ni","dha","Pa","ma","ga","Re","Sa"],
        pakad: [["ma","Pa","ni","dha","Pa","ma","ga","Re","Sa"]],
        vaadi: "dha",
        samvaadi: "ga",
        phrases: [
            ["Sa","Re","ma","Pa"],
            ["dha","ni","Sa","Re","Sa"],
            ["Sa","ni","dha","Pa","ma"],
            ["Pa","dha","ni","dha","Pa"],
            ["ma","ga","Re","Sa"],
            ["Sa","Re","ma","Pa","dha","ni","Sa"],
            ["Sa","ni","dha","Pa","ma","ga","Re","Sa"],
            ["ma","Pa","dha","ni","dha","Pa"],
            ["Re","ma","Pa","dha","Pa"],
            ["dha","ni","Sa","Re","ni","dha","Pa"],
            ["ma","Pa","ni","dha","Pa","ma","ga","Re","Sa"],
            ["Sa","Re","ma","Pa"],
            ["Pa","dha","ni","Sa"],
            ["Re","ma","Pa","dha","Pa","ma","ga","Re"],
            ["ni","dha","Pa","ma","Pa","ga","Re","Sa"]
        ]
    },
    {
        num: 20,
        id: "hamsadhwani",
        name: "Hamsadhwani",
        thaat: "Bilawal",
        aaroh: ["Sa","Re","Ga","Pa","Ni","Sa"],
        avaroh: ["Sa","Ni","Pa","Ga","Re","Sa"],
        pakad: [["Ga","Pa","Ni","Sa","Ni","Pa","Ga","Re","Sa"]],
        vaadi: "Sa",
        samvaadi: "Pa",
        phrases: [
            ["Sa","Re","Ga","Pa","Ni","Sa"],
            ["Pa","Ga","Re","Sa","Ni","Pa","Sa"],
            ["Ga","Pa","Ni","Pa","Ga","Re"],
            ["Ni","Pa","Ga","Re","Ga","Pa"],
            ["Re","Ga","Pa","Ni","Sa","Re","Sa"],
            ["Sa","Re","Ga","Pa","Ni","Sa"],
            ["Sa","Ni","Pa","Ga","Re","Sa"],
            ["Ga","Pa","Ni","Sa","Ni","Pa"],
            ["Sa","Re","Ga","Pa","Ga","Re","Sa"],
            ["Pa","Ni","Sa","Re","Ga","Re","Sa"],
            ["Ga","Pa","Ni","Pa","Ga","Re"],
            ["Sa","Re","Ga","Pa","Ni","Pa"],
            ["Ni","Sa","Re","Ga","Pa"],
            ["Pa","Ga","Re","Sa","Ni","Pa"],
            ["Sa","Re","Ga","Pa","Ni","Sa","Ga","Re","Sa"]
        ]
    },
    {
        num: 21,
        id: "miyan_ki_todi",
        name: "Miyan Ki Todi",
        thaat: "Todi",
        aaroh: ["Sa","re","ga","Ma","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","Ma","ga","re","Sa"],
        pakad: [["dha","Ni","Sa","re","ga","re","Sa"]],
        vaadi: "dha",
        samvaadi: "ga",
        phrases: [
            ["dha","Ni","Sa","re","ga","re","Sa"],
            ["Ma","ga","re","ga","re","Sa"],
            ["re","ga","Ma","dha","Ma","ga"],
            ["Sa","Ni","dha","Pa","Ma","ga","re"],
            ["ga","Ma","Pa","dha","Ni","Sa"],
            ["Sa","re","ga","Ma","dha","Ni","Sa"],
            ["Sa","Ni","dha","Pa","Ma","ga","re","Sa"],
            ["dha","Ni","Sa","re","ga","re","Sa"],
            ["Ma","dha","Ni","dha","Pa"],
            ["ga","Ma","dha","Pa","Ma","ga","re","Sa"],
            ["re","ga","Ma","dha","Ni"],
            ["Ni","dha","Pa","Ma","ga","re","ga","Ma"],
            ["Sa","re","ga","Ma","Pa"],
            ["dha","Ni","Sa","re","Ni","dha","Pa"],
            ["Ma","dha","Ni","Sa","Ni","dha","Pa"]
        ]
    },
    {
        num: 22,
        id: "ahir_bhairav",
        name: "Ahir Bhairav",
        thaat: "Bhairav",
        aaroh: ["Sa","re","Ga","ma","Pa","Dha","ni","Sa"],
        avaroh: ["Sa","ni","Dha","Pa","ma","Ga","re","Sa"],
        pakad: [["Ga","ma","Pa","Dha","ni","Dha","Pa","ma","Ga","re","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        phrases: [
            ["Sa","re","Ga","ma","Pa"],
            ["Dha","ni","Sa","ni","Dha","Pa"],
            ["Pa","ma","Ga","re","Sa"],
            ["Ga","ma","Pa","Dha","ni","Dha","Pa"],
            ["ni","Dha","Pa","ma","Ga","re","Sa"],
            ["Sa","re","Ga","ma","Pa","Dha","ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","Ga","re","Sa"],
            ["Ga","ma","Pa","Dha","ni","Dha","Pa"],
            ["Dha","ni","Sa","re","Sa"],
            ["re","Sa","ni","Dha","Pa"],
            ["ma","Pa","Dha","ni","Dha","Pa","ma","Ga","re","Sa"],
            ["Sa","re","Ga","ma","Pa"],
            ["Ga","ma","Pa","Dha","Pa"],
            ["ni","Dha","Pa","ma","Ga","ma","re","Sa"],
            ["Dha","ni","Sa","re","Ga","ma","Pa"]
        ]
    },
    {
        num: 23,
        id: "marwa",
        name: "Marwa",
        thaat: "Marwa",
        aaroh: ["Sa","re","Ga","Ma","Dha","Ni","re","Sa"],
        avaroh: ["Sa","Ni","Dha","Ma","Ga","re","Sa"],
        pakad: [["Dha","Ma","Ga","re","Ga","Ma","Dha","re","Ni","Dha","Sa"]],
        vaadi: "re",
        samvaadi: "Dha",
        phrases: [
            ["Dha","Ma","Ga","re","Ga","Ma","Dha"],
            ["re","Ni","Dha","Sa","re","Sa"],
            ["Ma","Dha","Ni","re","Sa"],
            ["re","Ni","Dha","Ma","Ga","re"],
            ["Ga","Ma","Dha","re","Ni","Dha","Ma","Ga"],
            ["Dha","Ni","re","Ga","Ma","Dha"],
            ["re","Ni","Dha","Ma","Ga","re"],
            ["re","Ga","Ma","Dha","Ni","Dha"],
            ["Ma","Dha","Sa","Ni","re","Ni","Dha"],
            ["Dha","Ma","Ga","re","Sa"],
            ["Ni","re","Ga","Ma","Dha","Ni","re","Sa"],
            ["re","Ni","Dha","Ma","Ga","re","Sa"],
            ["Ma","Dha","Ni","Dha","Sa"],
            ["Ga","Ma","Dha","Ni","re","Ni","Dha"],
            ["re","Ga","Ma","Ga","re","Sa"]
        ]
    },
    {
        num: 24,
        id: "puriya_dhanashri",
        name: "Puriya Dhanashri",
        thaat: "Poorvi",
        aaroh: ["Ni","re","Ga","Ma","Pa","dha","Pa","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","Ma","Ga","Ma","re","Ga","re","Sa"],
        pakad: [["Ni","re","Ga","Ma","Pa","Ma","Ga","Ma","re","Ga","re","Sa"]],
        vaadi: "Pa",
        samvaadi: "re",
        phrases: [
            ["Ni","re","Ga","Ma","Pa"],
            ["Ma","Pa","dha","Pa","Ma","Ga"],
            ["dha","Pa","Ma","Ga","re","Sa"],
            ["Pa","Ni","Sa","re","Ni","dha","Pa"],
            ["re","Ga","Ma","Pa","dha","Pa"],
            ["Ni","re","Ga","Ma","Pa","dha","Pa"],
            ["Ma","Pa","dha","Ni","Sa"],
            ["Sa","Ni","dha","Pa","Ma","Ga","Ma","re","Ga"],
            ["re","Ga","Ma","Pa"],
            ["dha","Pa","Ma","Ga","Ma","re","Ga"],
            ["Ni","re","Ga","Ma","Pa","dha","Ni","Sa"],
            ["re","Ni","dha","Pa"],
            ["Pa","dha","Pa","Ma","Ga"],
            ["Ma","dha","Ni","Sa","re","Ni","dha","Pa"],
            ["Ga","Ma","Pa","dha","Pa","Ma","Ga","re","Sa"]
        ]
    },
    {
        num: 32,
        id: "bhairavi",
        name: "Bhairavi",
        thaat: "Bhairavi",
        aaroh: ["Sa","re","ga","ma","Pa","dha","ni","Sa"],
        avaroh: ["Sa","ni","dha","Pa","ma","ga","re","Sa"],
        pakad: [["ma","ga","re","Sa","dha","ni","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "All Komal notes, uses all 12 notes in light variety",
        phrases: [
            ["Sa","re","ga","ma","Pa"],
            ["dha","Pa","ma","ga","re","Sa"],
            ["ni","Sa","ga","ma","dha","Pa"],
            ["Pa","dha","ni","Sa","ni","dha","Pa"],
            ["ma","ga","re","Sa"],
            ["Sa","re","ga","ma","Pa","dha","ni","Sa"],
            ["Sa","ni","dha","Pa","ma","ga","re","Sa"],
            ["ga","ma","Pa","dha","Pa"],
            ["dha","ni","Sa","re","ni","dha","Pa"],
            ["Pa","ma","ga","re","Sa"],
            ["Sa","re","ga","ma","Pa"],
            ["ma","Pa","dha","ni","Sa"],
            ["re","ga","ma","Pa","dha","Pa"],
            ["Sa","ni","dha","Pa","ma","Pa","ga","ma","re","Sa"],
            ["Pa","dha","ni","Sa","re","ni","dha","Pa"]
        ]
    },
    {
        num: 41,
        id: "malkauns",
        name: "Malkauns",
        thaat: "Bhairavi",
        aaroh: ["Sa","ga","ma","dha","ni","Sa"],
        avaroh: ["Sa","ni","dha","ma","ga","Sa"],
        pakad: [["dha","ni","dha","ma","ga","ma","ga","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Pentatonic, midnight, serious",
        phrases: [
            ["Sa","ga","ma","dha","ni","Sa"],
            ["Sa","ni","dha","ma","ga","ma","ga","Sa"],
            ["dha","ni","Sa","ma","ga","ma"],
            ["ga","ma","dha","ni","dha","ma"],
            ["ma","dha","ni","Sa","ni","dha","ma"],
            ["ga","ma","dha","ni","Sa","ga","Sa"],
            ["Sa","ni","dha","ma","ga","Sa"],
            ["dha","ni","Sa","ga","ma","dha","ma"],
            ["ma","ga","ma","dha","ni","dha","ma"],
            ["ni","dha","ma","ga","ma","ga","Sa"]
        ]
    },
    {
        num: 42,
        id: "chandrakauns",
        name: "Chandrakauns",
        thaat: "Bhairavi",
        aaroh: ["Sa","ga","ma","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","ma","ga","Sa"],
        pakad: [["ma","dha","Ni","dha","ma","ga","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Like Malkauns but with Shuddha Ni",
        phrases: [
            ["Sa","ga","ma","dha","Ni","Sa"],
            ["Sa","Ni","dha","ma","ga","ma","ga","Sa"],
            ["dha","Ni","Sa","ma","ga","ma"],
            ["ga","ma","dha","Ni","dha","ma"],
            ["ma","dha","Ni","Sa","Ni","dha","ma"],
            ["ga","ma","dha","Ni","Sa","ga","Sa"],
            ["Sa","Ni","dha","ma","ga","Sa"],
            ["dha","Ni","Sa","ga","ma","dha","ma"],
            ["ma","ga","ma","dha","Ni","dha","ma"],
            ["Ni","dha","ma","ga","ma","ga","Sa"]
        ]
    }
];
