import { Raga, Thaat } from './types';

export const THAAT_DATA: Thaat[] = [
    { id: "bilawal", name: "Bilawal", notes: ["Sa","Re","Ga","ma","Pa","Dha","Ni"] },
    { id: "kalyan", name: "Kalyan", notes: ["Sa","Re","Ga","Ma","Pa","Dha","Ni"] },
    { id: "khamaj", name: "Khamaj", notes: ["Sa","Re","Ga","ma","Pa","Dha","ni"] },
    { id: "kafi", name: "Kafi", notes: ["Sa","Re","ga","ma","Pa","Dha","ni"] },
    { id: "asavari", name: "Asavari", notes: ["Sa","Re","ga","ma","Pa","dha","ni"] },
    { id: "bhairavi", name: "Bhairavi", notes: ["Sa","re","ga","ma","Pa","dha","ni"] },
    { id: "bhairav", name: "Bhairav", notes: ["Sa","re","Ga","ma","Pa","dha","Ni"] },
    { id: "poorvi", name: "Poorvi", notes: ["Sa","re","Ga","Ma","Pa","dha","Ni"] },
    { id: "marwa", name: "Marwa", notes: ["Sa","re","Ga","Ma","Pa","Dha","Ni"] },
    { id: "todi", name: "Todi", notes: ["Sa","re","ga","Ma","Pa","dha","Ni"] }
];

export const RAGA_DATA: Raga[] = [
    {
        num: 1,
        id: "desi",
        name: "Desi",
        thaat: "Asavari",
        aaroh: ["Sa","Re","ma","Pa","Dha","ni","Sa"],
        avaroh: ["Sa","Pa","Dha","ma","Pa","Re","ga","Re","Sa"],
        pakad: [["Pa","Re","ga","Re","Sa","ni","Sa"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        identifyingFeature: "Mixes Shuddha and Komal Dha",
        phrases: [
            ["S","R","m","P"],
            ["m","P","D","m","P"],
            ["D","P","m","P","R","g","S"],
            ["R","n","S","R","g","S"],
            ["P","m","P","R","g","S"],
            ["S","R","m","P","D","m","P"],
            ["m","P","n","D","P"],
            ["P","D","m","P","g","S"],
            ["R","m","P","D","n","S"],
            ["S","n","D","P","m","P","g","S"]
        ]
    },
    {
        num: 2,
        id: "nat_bhairav",
        name: "Nat Bhairav",
        thaat: "Bhairav",
        aaroh: ["Sa","Re","Ga","ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","ma","Ga","Re","Sa"],
        pakad: [["ma","Pa","dha","Ni","Sa","Ni","dha","Pa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Shuddha Re in Bhairav scale",
        phrases: [
            ["S","R","G","m","P"],
            ["m","P","d","N","S"],
            ["S","N","d","P"],
            ["m","G","R","S"],
            ["S","R","G","m","P","d","P"],
            ["G","m","d","N","S"],
            ["N","S","d","N","d","P"],
            ["G","m","P","m","G","R","S"],
            ["S","R","G","m","R","S"],
            ["P","d","N","S","R","S"]
        ]
    },
    {
        num: 3,
        id: "bairagi",
        name: "Bairagi",
        thaat: "Bhairav",
        aaroh: ["Sa","re","ma","Pa","ni","Sa"],
        avaroh: ["Sa","ni","Pa","ma","re","Sa"],
        pakad: [["ni","Pa","ma","re","ni","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Pentatonic Bhairav (Revati with Komal Ni)",
        phrases: [
            ["S","r","m","P"],
            ["m","P","n","S"],
            ["S","n","P","m"],
            ["P","m","r","S"],
            ["n","S","r","m","P"],
            ["m","P","n","S","n","P"],
            ["r","m","P","n","P","m"],
            ["S","r","S","n","P"],
            ["P","n","S","r","m"],
            ["n","P","m","r","m","P"]
        ]
    },
    {
        num: 4,
        id: "kalingara",
        name: "Kalingara",
        thaat: "Bhairav",
        aaroh: ["Sa","re","Ga","ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","ma","Ga","re","Sa"],
        pakad: [["ma","Pa","dha","Ni","Sa"],["Pa","ma","Ga","re","Ga"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        identifyingFeature: "Lighter, playful Bhairav (no oscillation)",
        phrases: [
            ["S","r","G","m","P"],
            ["G","m","P","d","N","S"],
            ["S","N","d","P","m","G","r","S"],
            ["P","d","N","d","P"],
            ["m","P","d","P","m","G"],
            ["G","m","G","r","S"],
            ["S","r","G","m","P","m","G"],
            ["P","d","N","S","N","d","P"],
            ["m","G","r","G","S"],
            ["d","N","S","r","G","r","S"]
        ]
    },
    {
        num: 5,
        id: "poorvi",
        name: "Poorvi",
        thaat: "Poorvi",
        aaroh: ["Sa","re","Ga","Ma","P","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","P","Ma","Ga","re","Sa"],
        pakad: [["Pa","dha","Ma","Ga","re","Ga"],["Ma","dha","Ni","Sa"]],
        vaadi: "Ga",
        samvaadi: "Ni",
        identifyingFeature: "Uses both Mas sometimes, deeply serious",
        phrases: [
            ["S","r","G","M","P"],
            ["M","P","d","N","S"],
            ["S","N","d","P"],
            ["M","G","r","S"],
            ["P","d","P","M","G"],
            ["M","P","d","N","d","P"],
            ["r","G","M","P","M","G"],
            ["N","S","r","G","r","S"],
            ["P","M","G","M","r","G"],
            ["d","N","S","r","N","d","P"]
        ]
    },
    {
        num: 6,
        id: "gujari_todi",
        name: "Gujari Todi",
        thaat: "Todi",
        aaroh: ["Sa","re","ga","Ma","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Ma","ga","re","Sa"],
        pakad: [["dha","Ma","ga","re","ga","re","Sa"]],
        vaadi: "dha",
        samvaadi: "re",
        identifyingFeature: "Todi without Pa (Hexatonic)",
        phrases: [
            ["S","r","g","M","d"],
            ["M","d","N","S"],
            ["S","N","d","M","g","r","S"],
            ["d","N","S","r","g","r","S"],
            ["M","d","N","d","M"],
            ["g","M","d","M","g","r"],
            ["r","g","M","d","N"],
            ["N","d","M","g","r","g","M"],
            ["S","r","g","r","S"],
            ["d","N","S","r","g","M"]
        ]
    },
    {
        num: 7,
        id: "madhuvanti",
        name: "Madhuvanti",
        thaat: "Todi",
        aaroh: ["Sa","ga","Ma","Pa","Ni","Sa"],
        avaroh: ["Sa","Ni","Dha","Pa","Ma","ga","Re","Sa"],
        pakad: [["Ni","Sa","ga","Ma","Pa"]],
        vaadi: "Pa",
        samvaadi: "Sa",
        identifyingFeature: "Sweetness of honey (Madhu)",
        phrases: [
            ["N","S","g","M","P"],
            ["M","P","N","S"],
            ["S","N","D","P","M","g","R","S"],
            ["g","M","P","N","S"],
            ["P","N","S","g","R","S"],
            ["N","S","g","M","P","D","P"],
            ["M","P","N","S","N","D","P"],
            ["g","M","P","g","M","g","R","S"],
            ["P","N","S","g","M","P"],
            ["N","D","P","M","g","R"]
        ]
    },
    {
        num: 8,
        id: "bilaskhani_todi",
        name: "Bilaskhani Todi",
        thaat: "Bhairavi",
        aaroh: ["Sa","re","ga","Pa","dha","Sa"],
        avaroh: ["Sa","ni","dha","Pa","ma","ga","re","Sa"],
        pakad: ["dha","Pa","ma","ga","re","ga","re","Sa"],
        phrases: [
            ["Sa","re","ga","Pa","dha","Sa"],
            ["ni","dha","Pa","ma","ga","re","Sa"],
            ["ga","Pa","dha","Sa","re","Sa"],
            ["ni","dha","Pa","ma","ga","re"],
            ["dha","Pa","ma","ga","re","Sa"],
            ["S","r","g","P","d","S"],
            ["S","n","d","P"],
            ["d","P","m","g","r","S"],
            ["r","n","S","r","g","P"],
            ["g","P","d","S","n","d","P"],
            ["d","P","m","g","r","g","r","S"],
            ["r","g","P","d","n","d","P"],
            ["S","r","g","P","m","g","r","S"],
            ["P","d","S","r","g","r","S"],
            ["n","d","P","m","g","r","S"]
        ],
        vaadi: "dha",
        samvaadi: "ga"
    },
    {
        num: 9,
        id: "yaman",
        name: "Yaman",
        thaat: "Kalyan",
        aaroh: ["Ni","Re","Ga","Ma","Dha","Ni","Sa"],
        avaroh: ["Sa","Ni","Dha","Pa","Ma","Ga","Re","Sa"],
        pakad: ["Ni","Re","Ga","Re","Sa","Pa","Ma","Ga","Re","Sa"],
        phrases: [
            ["Ni","Re","Ga","Re","Sa"],
            ["Ma","Pa","Dha","Ni","Sa"],
            ["Pa","Ma","Ga","Re","Ni","Re","Sa"],
            ["Ni","Dha","Pa","Ma","Ga"],
            ["Ga","Ma","Pa","Re","Sa"],
            ["N","R","G","M","P"],
            ["M","D","N","S"],
            ["S","N","D","P","M","G","R","S"],
            ["N","R","G","M","P","D","N","S"],
            ["P","M","G","R","S"],
            ["N","R","S","N","D","P"],
            ["M","D","N","D","P"],
            ["G","M","P","M","G","R"],
            ["N","R","G","M","P","M","G"],
            ["P","D","N","S","N","D","P"]
        ],
        vaadi: "Ga",
        samvaadi: "Ni"
    },
    {
        num: 10,
        id: "bhupali",
        name: "Bhupali",
        thaat: "Kalyan",
        aaroh: ["Sa","Re","Ga","Pa","Dha","Sa"],
        avaroh: ["Sa","Dha","Pa","Ga","Re","Sa"],
        pakad: ["Sa","Re","Ga","Pa","Ga","Re","Sa"],
        phrases: [
            ["Ga","Pa","Dha","Sa","Dha","Pa","Ga"],
            ["Sa","Re","Ga","Pa","Ga","Re","Sa"],
            ["Pa","Ga","Dha","Pa","Ga","Re","Sa"],
            ["Sa","Dha","Pa","Ga","Re","Sa","Dha","Sa"],
            ["Dha","Sa","Re","Ga","Pa"],
            ["S","R","G","P","D","S"],
            ["S","D","P","G","R","S"],
            ["G","P","D","S","D","P"],
            ["S","R","G","P","G","R","S"],
            ["P","D","S","R","S","D","P"],
            ["G","P","D","P","G","R"],
            ["S","R","G","R","S","D"],
            ["D","S","R","G","P"],
            ["G","P","D","S","R","G","R","S"],
            ["P","G","D","P","G","R","S"]
        ],
        vaadi: "Ga",
        samvaadi: "Dha"
    },
    {
        num: 11,
        id: "shivranjani",
        name: "Shivranjani",
        thaat: "Kafi",
        aaroh: ["Sa","Re","ga","Pa","Dha","Sa"],
        avaroh: ["Sa","Dha","Pa","ga","Re","Sa"],
        pakad: ["Sa","Re","ga","Pa","Dha","Pa","ga","Re","Sa"],
        phrases: [
            ["Re","ga","Pa","Dha","Pa","ga","Re"],
            ["Sa","Re","ga","Pa","Dha","Sa"],
            ["Dha","Pa","ga","Re","Sa"],
            ["ga","Re","Sa","Dha","Sa"],
            ["Pa","Dha","Sa","Re","ga","Re","Sa"],
            ["S","R","g","P","D","S"],
            ["S","D","P","g","R","S"],
            ["R","g","P","D","P","g","R"],
            ["S","R","g","P","g","R","S"],
            ["P","D","S","R","g","R","S"],
            ["g","P","D","S","D","P"],
            ["S","R","g","S","D","P"],
            ["D","S","R","g","P","D"],
            ["g","P","D","S","R","S"],
            ["P","D","P","g","R","S"]
        ],
        vaadi: "Pa",
        samvaadi: "Sa"
    },
    {
        num: 12,
        id: "bhairav",
        name: "Bhairav",
        thaat: "Bhairav",
        aaroh: ["Sa","re","Ga","ma","Pa","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","ma","Ga","re","Sa"],
        pakad: ["Ga","ma","dha","Pa"],
        phrases: [
            ["Ga","ma","dha","dha","Pa"],
            ["Ga","ma","re","re","Sa"],
            ["Ni","re","Sa","Ga","ma","Pa"],
            ["Pa","Ga","ma","dha","Ni","Sa"],
            ["dha","dha","Pa","ma","Ga","ma","re","Sa"],
            ["S","r","G","m","P"],
            ["G","m","d","P"],
            ["d","d","P"],
            ["G","m","r","r","S"],
            ["N","S","r","G","m","P"],
            ["P","d","N","S"],
            ["S","N","d","P","m","G","r","S"],
            ["G","m","P","d","P"],
            ["m","P","G","m","r","S"],
            ["N","r","S","G","m","P"]
        ],
        vaadi: "dha",
        samvaadi: "re"
    },
    {
        num: 13,
        id: "desh",
        name: "Desh",
        thaat: "Khamaj",
        aaroh: ["Sa","Re","ma","Pa","Ni","Sa"],
        avaroh: ["Sa","ni","Dha","Pa","ma","Ga","Re","Ga","Sa"],
        pakad: ["Re","ma","Pa","ni","Dha","Pa"],
        phrases: [
            ["Re","ma","Pa","Ni","Sa"],
            ["Sa","ni","Dha","Pa","ma","Ga","Re"],
            ["Re","Ga","Sa","Re","ma","Ga"],
            ["Pa","Dha","Pa","ma","Ga","Re","Ga","Sa"],
            ["Ni","Sa","Re","ni","Dha","Pa"],
            ["S","R","m","P","N","S"],
            ["S","n","D","P","m","G","R","S"],
            ["R","m","P","N","D","P"],
            ["m","P","n","D","P"],
            ["D","P","m","G","R","G","S"],
            ["R","m","P","N","S","R","n","D","P"],
            ["N","S","R","n","D","P"],
            ["m","P","N","S"],
            ["S","R","m","G","R","S"],
            ["P","D","P","m","G","R","S"]
        ],
        vaadi: "Re",
        samvaadi: "Pa"
    },
    {
        num: 14,
        id: "durga",
        name: "Durga",
        thaat: "Bilawal",
        aaroh: ["Sa","Re","ma","Pa","Dha","Sa"],
        avaroh: ["Sa","Dha","Pa","ma","Re","Sa"],
        pakad: ["Dha","ma","Pa","Dha","ma","Re"],
        phrases: [
            ["Sa","Re","ma","Pa","Dha","Sa"],
            ["Dha","Pa","ma","Re","Sa"],
            ["ma","Pa","Dha","ma","Re","Sa"],
            ["Sa","Re","Sa","Dha","Sa"],
            ["Dha","Sa","Dha","Pa","ma","Re"],
            ["S","R","m","P","D","S"],
            ["S","D","P","m","R","S"],
            ["m","P","D","S","D","P"],
            ["D","m","P","D","m","R"],
            ["S","R","m","P","m","R","S"],
            ["D","S","R","m","R","S"],
            ["m","P","D","S","R","S","D","P"],
            ["P","D","m","P","m","R"],
            ["S","R","S","D","S"],
            ["D","P","m","R","m","P","D","S"]
        ],
        vaadi: "ma",
        samvaadi: "Sa"
    },
    {
        num: 15,
        id: "kedar",
        name: "Kedar",
        thaat: "Kalyan",
        aaroh: ["Sa","ma","Ga","Pa","Ni","Dha","Sa"],
        avaroh: ["Sa","Ni","Dha","Pa","Ma","Pa","Dha","Pa","ma","Re","Sa"],
        pakad: ["Sa","ma","Ga","Pa","ma","Re","Sa"],
        phrases: [
            ["Sa","ma","Ga","Pa"],
            ["Ma","Pa","Dha","Pa","ma"],
            ["Pa","ma","Re","Sa"],
            ["Sa","Ni","Dha","Pa"],
            ["Dha","Pa","Ma","Pa","Ga","ma","Re","Sa"],
            ["S","m","G","P"],
            ["m","P","D","P","m"],
            ["P","m","R","S"],
            ["S","m","G","P","m","D","P"],
            ["D","N","D","P"],
            ["S","R","S","m","G","P"],
            ["m","P","D","P","M","P","D","P","m"],
            ["P","m","R","S","R","S"],
            ["S","m","G","P","N","D","S"],
            ["S","N","D","P","m","G","P","m","R","S"]
        ],
        vaadi: "ma",
        samvaadi: "Sa"
    },
    {
        num: 16,
        id: "bageshri",
        name: "Bageshri",
        thaat: "Kafi",
        aaroh: ["Sa","ga","ma","Dha","ni","Sa"],
        avaroh: ["Sa","ni","Dha","ma","Pa","Dha","ga","Re","Sa"],
        pakad: ["Dha","ni","Sa","ma","ga","Re","Sa"],
        phrases: [
            ["Sa","ga","ma","Dha","ni","Sa"],
            ["Sa","ni","Dha","ma","Pa","Dha","ga"],
            ["ma","Pa","Dha","ni","Dha","ma"],
            ["ga","Re","Sa","ni","Dha","Sa"],
            ["Dha","ni","Sa","ma","ga","Re","Sa"],
            ["S","g","m","D","n","S"],
            ["S","n","D","m","P","D","g","m","g","R","S"],
            ["D","n","S","m","g","m"],
            ["g","m","D","n","D","m"],
            ["m","P","D","g","m","g","R","S"],
            ["n","D","m","P","D","n","S"],
            ["S","n","D","m","g","R","S"],
            ["g","m","D","n","S","n","D"],
            ["m","D","n","D","m","g","R"],
            ["S","g","m","g","R","S"]
        ],
        vaadi: "ma",
        samvaadi: "Sa"
    },
    {
        num: 17,
        id: "bhimpalasi",
        name: "Bhimpalasi",
        thaat: "Kafi",
        aaroh: ["ni","Sa","ga","ma","Pa","ni","Sa"],
        avaroh: ["Sa","ni","Dha","Pa","ma","ga","Re","Sa"],
        pakad: ["ni","Sa","ga","ma","Pa","ga","ma","ga","Re","Sa"],
        phrases: [
            ["ni","Sa","ma","Pa","ga","ma"],
            ["ma","Pa","ni","Dha","Pa"],
            ["Pa","ma","ga","Re","Sa"],
            ["Sa","ni","Dha","Pa","ma","ga","Re"],
            ["ni","Sa","ga","ma","Pa","ni","Sa"],
            ["n","S","g","m","P","n","S"],
            ["S","n","D","P","m","g","R","S"],
            ["n","S","m","P","g","m"],
            ["m","P","n","D","P"],
            ["P","m","g","R","S"],
            ["n","S","g","m","P"],
            ["P","n","S","g","R","S"],
            ["m","P","g","m","P","n","S"],
            ["S","n","D","P","m","P","g","m"],
            ["g","m","P","n","D","P"]
        ],
        vaadi: "ma",
        samvaadi: "Sa"
    },
    {
        num: 18,
        id: "darbari",
        name: "Darbari Kanada",
        thaat: "Asavari",
        aaroh: ["Sa","Re","ga","ma","Pa","dha","ni","Sa"],
        avaroh: ["Sa","dha","ni","Pa","ma","Pa","ga","ma","Re","Sa"],
        pakad: ["ni","Pa","ma","Pa","ga","ma","Re","Sa"],
        phrases: [
            ["Sa","Re","ga","ma","Pa"],
            ["dha","ni","Pa","ma","Pa"],
            ["ga","ma","Re","Sa"],
            ["Pa","dha","ni","Sa"],
            ["Sa","dha","ni","Pa","ga","ma","Re","Sa"],
            ["n","S","R","g","R","S"],
            ["d","n","P","m","P","g","m","R","S"],
            ["S","R","g","m","P"],
            ["P","d","n","P","m","P"],
            ["g","m","R","S"],
            ["S","d","n","P"],
            ["P","m","P","g","m","R","S"],
            ["n","S","R","g","m","P"],
            ["d","n","S","R","g","R","S"],
            ["m","P","d","n","S"]
        ],
        vaadi: "Re",
        samvaadi: "Pa"
    },
    {
        num: 19,
        id: "jaunpuri",
        name: "Jaunpuri",
        thaat: "Asavari",
        aaroh: ["Sa","Re","ma","Pa","dha","ni","Sa"],
        avaroh: ["Sa","ni","dha","Pa","ma","ga","Re","Sa"],
        pakad: ["ma","Pa","ni","dha","Pa","ma","ga","Re","Sa"],
        phrases: [
            ["Sa","Re","ma","Pa"],
            ["dha","ni","Sa","Re","Sa"],
            ["Sa","ni","dha","Pa","ma"],
            ["Pa","dha","ni","dha","Pa"],
            ["ma","ga","Re","Sa"],
            ["S","R","m","P","d","n","S"],
            ["S","n","d","P","m","g","R","S"],
            ["m","P","d","n","d","P"],
            ["R","m","P","d","P"],
            ["d","n","S","R","n","d","P"],
            ["m","P","n","d","P","m","g","R","S"],
            ["S","R","m","P"],
            ["P","d","n","S"],
            ["R","m","P","d","P","m","g","R"],
            ["n","d","P","m","P","g","R","S"]
        ],
        vaadi: "dha",
        samvaadi: "ga"
    },
    {
        num: 20,
        id: "hamsadhwani",
        name: "Hamsadhwani",
        thaat: "Bilawal",
        aaroh: ["Sa","Re","Ga","Pa","Ni","Sa"],
        avaroh: ["Sa","Ni","Pa","Ga","Re","Sa"],
        pakad: ["Ga","Pa","Ni","Sa","Ni","Pa","Ga","Re","Sa"],
        phrases: [
            ["Sa","Re","Ga","Pa","Ni","Sa"],
            ["Pa","Ga","Re","Sa","Ni","Pa","Sa"],
            ["Ga","Pa","Ni","Pa","Ga","Re"],
            ["Ni","Pa","Ga","Re","Ga","Pa"],
            ["Re","Ga","Pa","Ni","Sa","Re","Sa"],
            ["S","R","G","P","N","S"],
            ["S","N","P","G","R","S"],
            ["G","P","N","S","N","P"],
            ["S","R","G","P","G","R","S"],
            ["P","N","S","R","G","R","S"],
            ["G","P","N","P","G","R"],
            ["S","R","G","P","N","P"],
            ["N","S","R","G","P"],
            ["P","G","R","S","N","P"],
            ["S","R","G","P","N","S","G","R","S"]
        ],
        vaadi: "Sa",
        samvaadi: "Pa"
    },
    {
        num: 21,
        id: "miyan_ki_todi",
        name: "Miyan Ki Todi",
        thaat: "Todi",
        aaroh: ["Sa","re","ga","Ma","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","Ma","ga","re","Sa"],
        pakad: ["dha","Ni","Sa","re","ga","re","Sa"],
        phrases: [
            ["dha","Ni","Sa","re","ga","re","Sa"],
            ["Ma","ga","re","ga","re","Sa"],
            ["re","ga","Ma","dha","Ma","ga"],
            ["Sa","Ni","dha","Pa","Ma","ga","re"],
            ["ga","Ma","Pa","dha","Ni","Sa"],
            ["S","r","g","M","d","N","S"],
            ["S","N","d","P","M","g","r","S"],
            ["d","N","S","r","g","r","S"],
            ["M","d","N","d","P"],
            ["g","M","d","P","M","g","r","S"],
            ["r","g","M","d","N"],
            ["N","d","P","M","g","r","g","M"],
            ["S","r","g","M","P"],
            ["d","N","S","r","N","d","P"],
            ["M","d","N","S","N","d","P"]
        ],
        vaadi: "dha",
        samvaadi: "ga"
    },
    {
        num: 22,
        id: "ahir_bhairav",
        name: "Ahir Bhairav",
        thaat: "Bhairav",
        aaroh: ["Sa","re","Ga","ma","Pa","Dha","ni","Sa"],
        avaroh: ["Sa","ni","Dha","Pa","ma","Ga","re","Sa"],
        pakad: ["Ga","ma","Pa","Dha","ni","Dha","Pa","ma","Ga","re","Sa"],
        phrases: [
            ["Sa","re","Ga","ma","Pa"],
            ["Dha","ni","Sa","ni","Dha","Pa"],
            ["Pa","ma","Ga","re","Sa"],
            ["Ga","ma","Pa","Dha","ni","Dha","Pa"],
            ["ni","Dha","Pa","ma","Ga","re","Sa"],
            ["S","r","G","m","P","D","n","S"],
            ["S","n","D","P","m","G","r","S"],
            ["G","m","P","D","n","D","P"],
            ["D","n","S","r","S"],
            ["r","S","n","D","P"],
            ["m","P","D","n","D","P","m","G","r","S"],
            ["S","r","G","m","P"],
            ["G","m","P","D","P"],
            ["n","D","P","m","G","m","r","S"],
            ["D","n","S","r","G","m","P"]
        ],
        vaadi: "ma",
        samvaadi: "Sa"
    },
    {
        num: 23,
        id: "marwa",
        name: "Marwa",
        thaat: "Marwa",
        aaroh: ["Sa","re","Ga","Ma","Dha","Ni","re","Sa"],
        avaroh: ["Sa","Ni","Dha","Ma","Ga","re","Sa"],
        pakad: ["Dha","Ma","Ga","re","Ga","Ma","Dha","re","Ni","Dha","Sa"],
        phrases: [
            ["Dha","Ma","Ga","re","Ga","Ma","Dha"],
            ["re","Ni","Dha","Sa","re","Sa"],
            ["Ma","Dha","Ni","re","Sa"],
            ["re","Ni","Dha","Ma","Ga","re"],
            ["Ga","Ma","Dha","re","Ni","Dha","Ma","Ga"],
            ["D","N","r","G","M","D"],
            ["r","N","D","M","G","r"],
            ["r","G","M","D","N","D"],
            ["M","D","S","N","r","N","D"],
            ["D","M","G","r","S"],
            ["N","r","G","M","D","N","r","S"],
            ["r","N","D","M","G","r","S"],
            ["M","D","N","D","S"],
            ["G","M","D","N","r","N","D"],
            ["r","G","M","G","r","S"]
        ],
        vaadi: "re",
        samvaadi: "Dha"
    },
    {
        num: 24,
        id: "puriya_dhanashri",
        name: "Puriya Dhanashri",
        thaat: "Poorvi",
        aaroh: ["Ni","re","Ga","Ma","Pa","dha","Pa","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","Pa","Ma","Ga","Ma","re","Ga","re","Sa"],
        pakad: ["Ni","re","Ga","Ma","Pa","Ma","Ga","Ma","re","Ga","re","Sa"],
        phrases: [
            ["Ni","re","Ga","Ma","Pa"],
            ["Ma","Pa","dha","Pa","Ma","Ga"],
            ["dha","Pa","Ma","Ga","re","Sa"],
            ["Pa","Ni","Sa","re","Ni","dha","Pa"],
            ["re","Ga","Ma","Pa","dha","Pa"],
            ["N","r","G","M","P","d","P"],
            ["M","P","d","N","S"],
            ["S","N","d","P","M","G","M","r","G"],
            ["r","G","M","P"],
            ["d","P","M","G","M","r","G"],
            ["N","r","G","M","P","d","N","S"],
            ["r","N","d","P"],
            ["P","d","P","M","G"],
            ["M","d","N","S","r","N","d","P"],
            ["G","M","P","d","P","M","G","r","S"]
        ],
        vaadi: "Pa",
        samvaadi: "re"
    },
    {
        num: 32,
        id: "bhairavi",
        name: "Bhairavi",
        thaat: "Bhairavi",
        aaroh: ["Sa","re","ga","ma","Pa","dha","ni","Sa"],
        avaroh: ["Sa","ni","dha","Pa","ma","ga","re","Sa"],
        pakad: [["ma","ga","re","Sa","dha","ni","Sa"]],
        phrases: [
            ["Sa","re","ga","ma","Pa"],
            ["dha","Pa","ma","ga","re","Sa"],
            ["ni","Sa","ga","ma","dha","Pa"],
            ["Pa","dha","ni","Sa","ni","dha","Pa"],
            ["ma","ga","re","Sa"],
            ["S","r","g","m","P","d","n","S"],
            ["S","n","d","P","m","g","r","S"],
            ["g","m","P","d","P"],
            ["d","n","S","r","n","d","P"],
            ["P","m","g","r","S"],
            ["S","r","g","m","P"],
            ["m","P","d","n","S"],
            ["r","g","m","P","d","P"],
            ["S","n","d","P","m","P","g","m","r","S"],
            ["P","d","n","S","r","n","d","P"]
        ],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "All Komal notes, uses all 12 notes in light variety"
    },
    {
        num: 41,
        id: "malkauns",
        name: "Malkauns",
        thaat: "Bhairavi",
        aaroh: ["Sa","ga","ma","dha","ni","Sa"],
        avaroh: ["Sa","ni","dha","ma","ga","Sa"],
        pakad: [["dha","ni","dha","ma","ga","ma","ga","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Pentatonic, midnight, serious",
        phrases: [
            ["S","g","m","d","n","S"],
            ["S","n","d","m","g","m","g","S"],
            ["d","n","S","m","g","m"],
            ["g","m","d","n","d","m"],
            ["m","d","n","S","n","d","m"],
            ["g","m","d","n","S","g","S"],
            ["S","n","d","m","g","S"],
            ["d","n","S","g","m","d","m"],
            ["m","g","m","d","n","d","m"],
            ["n","d","m","g","m","g","S"]
        ]
    },
    {
        num: 42,
        id: "chandrakauns",
        name: "Chandrakauns",
        thaat: "Bhairavi",
        aaroh: ["Sa","ga","ma","dha","Ni","Sa"],
        avaroh: ["Sa","Ni","dha","ma","ga","Sa"],
        pakad: [["ma","dha","Ni","dha","ma","ga","Sa"]],
        vaadi: "ma",
        samvaadi: "Sa",
        identifyingFeature: "Like Malkauns but with Shuddha Ni",
        phrases: [
            ["S","g","m","d","N","S"],
            ["S","N","d","m","g","m","g","S"],
            ["d","N","S","m","g","m"],
            ["g","m","d","N","d","m"],
            ["m","d","N","S","N","d","m"],
            ["g","m","d","N","S","g","S"],
            ["S","N","d","m","g","S"],
            ["d","N","S","g","m","d","m"],
            ["m","g","m","d","N","d","m"],
            ["N","d","m","g","m","g","S"]
        ]
    }
];
